export { ExternalIdSessionStateMachine } from "./auth/external-id-session.js";
export type { AuthState, AcquireTokenResult } from "./auth/external-id-session.js";
export { buildMsalConfiguration } from "./auth/msal-config.js";
export type { ExternalIdClientConfig } from "./auth/msal-config.js";
export { getJoinToken } from "./auth/join-token-caller.js";
export type { JoinTokenResponse } from "./auth/join-token-caller.js";
export { SessionBootstrapStore } from "./session/bootstrap-store.js";
export type { BootstrapPayload } from "./session/bootstrap-store.js";
export { sendHeartbeat } from "./session/heartbeat-caller.js";
export type { HeartbeatResponse } from "./session/heartbeat-caller.js";
